set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g status-style "bg=default"
set -g status-left-length 100

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g status-right ""
set -g status-left "#S"

set -g automatic-rename on

set -g mouse on
set -g focus-events off
setw -g aggressive-resize off
setw -g clock-mode-style 24
set -g escape-time 500
set -g history-limit 5000


bind f run-shell "tmux neww ~/.config/scripts/tmux-sessioniser.sh"
# bind b run-shell "~/.config/scripts/tmux-baconator.sh"
bind F run-shell "tmux neww ~/.config/scripts/tmux-list-sessions"

bind r source-file ~/.tmux.conf
bind D detach
bind d switch-client -t root

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

