[bootstrap.repos]
"~/.dotfiles" = { url = "git@github.com:vincent-thomas/.dotfiles" }
"~/.config/nvim" = { url = "git@github.com:vincent-thomas/nvim.git" }

[bootstrap.remote]
source = "."

[bootstrap.remote.hosts.dev]
host = "dev"
user = "ubuntu"
port = 22
identity_file = "~/.ssh/work"
bootstrap_command = '''
if [ ! -x "$HOME/.local/bin/mise" ]; then
  curl -fsSL https://mise.run | sh
fi
'''

[bootstrap.remote.hosts.orb]
host = "orb"
identity_file = "~/.ssh/work"
user = "vt"
port = 22
bootstrap_command = '''
if [ ! -x "$HOME/.local/bin/mise" ]; then
  curl -fsSL https://mise.run | sh
fi
'''

[bootstrap.packages]
"brew:zsh" = "latest"

# [settings]
# lockfile = true
# dotfiles.default_mode = "symlink"

[dotfiles]
# "~/.config/alacritty" = {}
"~/.config/mise/conf.d/global.toml" = {
  source = "~/.dotfiles/.config/mise/conf.d/global.toml", mode = "symlink",
}
"~/.config/mise/conf.d/nvim.toml" = {
  source = "~/.config/nvim/mise.toml", mode = "symlink",
}
"~/.gitconfig" = "git/gitconfig"
# "~/.tmux.conf" = {}
"~/.zshrc/mise_activate" = { block = "eval \"$(mise activate zsh)\"" }
"~/.zshrc/config" = { source = "zsh/zshrc", template = "tera" }
"~/.zprofile/setup_path" = { block = "export PATH=\"$PATH:$HOME/.local/bin/mise\"" }
"~/.zprofile/mise_activate_shims" = { block = "eval \"$(mise activate zsh --shims)\"" }
