[settings]
lockfile = true
dotfiles.default_mode = "copy"
minimum_release_age = "0"

[tools]
# langs
bun = "latest"
rust = "latest"

# harnesses
codex = "latest"

# cli tools
fd = "latest"
ripgrep = "latest"
fzf = "latest"
bat = "latest"

# dev
neovim = "latest"
pitchfork = "latest"
tmux = "latest"

[env]
EDITOR="nvim"
