PS1='%F{183}%m%F{8} :: %F{14}%~%F{yellow} $ %f'

source <(fzf --zsh)

alias v="nvim"
alias cargo="c"

. /Users/vt/.config/op/plugins.sh

fpath+=('/Users/vt/.local/share/zsh/site-functions')
autoload -Uz compinit && compinit
