PS1='%F{183}%m%F{8} :: %F{14}%~%F{yellow} $ %f'

export PATH="$PATH:/Users/vt/.local/bin"

source <(fzf --zsh)

# ssh
eval "$(ssh-agent)" > /dev/null
ssh-add ~/.ssh/github 2> /dev/null
# end

# Edit command in editor command
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line
# end


bindkey -s '^Xgc' 'git commit -m ""\C-b'

# suffix aliases
alias -s md="bat"
# end

alias v="nvim"
alias cargo="c"

. /Users/vt/.config/op/plugins.sh

fpath+=('/Users/vt/.local/share/zsh/site-functions')
autoload -Uz compinit && compinit
